In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
import tensorflow as tf
import os
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout,Conv2D, MaxPooling2D,Flatten
import numpy as np
import cv2

In [0]:
import random
import glob
import shutil

In [0]:
base_path = '/content/drive/My Drive/Hackathon-Alphacode/dataset'

In [0]:
categories = ['DalaiLama','ArseneWenger','GeneliaDsouza', 'LuizSuarez', 'SergioAguero']
Img_size = 150
training_data = []

In [0]:
count=0
for folder in categories:t
  #path = os.path.join(os.path.dir(base_dir, folder))
  path = f'{base_path}/{folder}'
  for img in os.listdir(path):
    img_path = f'{path}/{img}'
    label = categories.index(folder)
    try:
      img_arr = cv2.imread(img_path)
      new_arr = cv2.resize(img_arr, (Img_size, Img_size))
      training_data.append([new_arr, label])
    except:
      count += 1
      print(count, end=' ')


In [7]:
print(len(training_data))


2709


In [0]:
random.shuffle(training_data)

In [0]:
x,y=[],[]
for feature, labels in training_data:
  x.append(feature)
  y.append(labels)

In [0]:
x = np.array(x).reshape(-1, Img_size,Img_size, 3)

In [0]:
x = x/255

In [13]:
print(x)

[[[[0.31764706 0.31764706 0.45882353]
   [0.32156863 0.32156863 0.4627451 ]
   [0.3254902  0.3254902  0.46666667]
   ...
   [0.43921569 0.29019608 0.23921569]
   [0.43529412 0.29019608 0.23137255]
   [0.43137255 0.29019608 0.22745098]]

  [[0.33333333 0.33333333 0.47058824]
   [0.33333333 0.33333333 0.4745098 ]
   [0.3372549  0.3372549  0.47843137]
   ...
   [0.45490196 0.30588235 0.24705882]
   [0.45098039 0.30196078 0.23921569]
   [0.45098039 0.30196078 0.23137255]]

  [[0.3372549  0.3372549  0.47843137]
   [0.34117647 0.34117647 0.48235294]
   [0.34509804 0.34509804 0.48627451]
   ...
   [0.47843137 0.32156863 0.25098039]
   [0.4745098  0.32156863 0.24705882]
   [0.46666667 0.30980392 0.23529412]]

  ...

  [[0.26666667 0.16470588 0.10980392]
   [0.2745098  0.17254902 0.11764706]
   [0.28235294 0.18039216 0.1254902 ]
   ...
   [0.05490196 0.03529412 0.03137255]
   [0.05490196 0.03529412 0.03137255]
   [0.05490196 0.03529412 0.03137255]]

  [[0.25882353 0.15686275 0.10196078]
   [0.2

In [0]:
from tensorflow.keras.applications import MobileNetV2

In [13]:
base_model = MobileNetV2(input_shape=(Img_size,Img_size, 3), include_top=False, weights='imagenet')
base_model.trainable = False

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


/usr/local/lib/python3.6/dist-packages/keras_applications/mobilenet_v2.py:294: UserWarning: `input_shape` is undefined or non-square, or `rows` is not in [96, 128, 160, 192, 224]. Weights for input shape (224, 224) will be loaded as the default.
  warnings.warn('`input_shape` is undefined or non-square, '


9412608/9406464 [==============================] - 2s 0us/step


In [16]:
base_model.summary()

Model: "mobilenetv2_1.00_224"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 150, 150, 3) 0                                            
__________________________________________________________________________________________________
Conv1_pad (ZeroPadding2D)       (None, 151, 151, 3)  0           input_1[0][0]                    
__________________________________________________________________________________________________
Conv1 (Conv2D)                  (None, 75, 75, 32)   864         Conv1_pad[0][0]                  
__________________________________________________________________________________________________
bn_Conv1 (BatchNormalization)   (None, 75, 75, 32)   128         Conv1[0][0]                      
_______________________________________________________________________________

In [0]:
model = Sequential()

In [0]:
model.add(base_model)


model.add(MaxPooling2D(pool_size=(3,3)))  #MaxPooling is done to neuron mismatch

model.add(Flatten())
model.add(Dense(64, activation='relu'))
model.add(Dense(128, activation='relu'))

model.add(Dense(5, activation='softmax'))

In [0]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [17]:
model.fit(x, y,epochs = 9, batch_size=48, validation_split=0.2)

Train on 2167 samples, validate on 542 samples
Epoch 1/9
2167/2167 [==============================] - 9s 4ms/sample - loss: 0.9619 - acc: 0.6354 - val_loss: 1.1994 - val_acc: 0.5498
Epoch 2/9
2167/2167 [==============================] - 4s 2ms/sample - loss: 0.4034 - acc: 0.8500 - val_loss: 0.9237 - val_acc: 0.6255
Epoch 3/9
2167/2167 [==============================] - 4s 2ms/sample - loss: 0.3575 - acc: 0.8648 - val_loss: 1.7234 - val_acc: 0.4613
Epoch 4/9
2167/2167 [==============================] - 4s 2ms/sample - loss: 0.2483 - acc: 0.9040 - val_loss: 1.0135 - val_acc: 0.6624
Epoch 5/9
2167/2167 [==============================] - 4s 2ms/sample - loss: 0.2493 - acc: 0.9100 - val_loss: 0.7135 - val_acc: 0.7472
Epoch 6/9
2167/2167 [==============================] - 4s 2ms/sample - loss: 0.1923 - acc: 0.9234 - val_loss: 0.8062 - val_acc: 0.7306
Epoch 7/9
2167/2167 [==============================] - 4s 2ms/sample - loss: 0.1752 - acc: 0.9372 - val_loss: 0.7274 - val_acc: 0.7786
Epoch 8/

In [0]:
model.save('/content/drive/My Drive/Hackathon-Alphacode/CelebModel2.h5')

In [27]:
score = model.evaluate(x,y, verbose=1)
print('Accuracy : ',score[0])
print('Loss : ',score[1])

2709/2709 [==============================] - 6s 2ms/sample - loss: 0.8267 - acc: 0.7401
Accuracy :  0.8266971330882087
Loss :  0.74012554


In [34]:
import cv2
import numpy as np
from tensorflow.keras.models import load_model
from google.colab import drive
drive.mount('/content/drive')


model = load_model('/content/drive/My Drive/Hackathon-Alphacode/CelebModel.h5')

#categories = ['DalaiLama','ArseneWenger','GeneliaDsouza', 'LuizSuarez', 'SergioAguero']

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [35]:
image_url = 'https://e0.365dm.com/18/08/2048x1152/skysports-sergio-aguero-manchester_4394682.jpg'
!wget $image_url

--2019-09-24 16:42:34--  https://e0.365dm.com/18/08/2048x1152/skysports-sergio-aguero-manchester_4394682.jpg
Resolving e0.365dm.com (e0.365dm.com)... 8.250.213.252, 8.250.235.252, 8.249.31.252, ...
Connecting to e0.365dm.com (e0.365dm.com)|8.250.213.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 211577 (207K) [image/jpeg]
Saving to: ‘skysports-sergio-aguero-manchester_4394682.jpg.2’

skysports-sergio-ag 100%[===================>] 206.62K   702KB/s    in 0.3s    

2019-09-24 16:42:35 (702 KB/s) - ‘skysports-sergio-aguero-manchester_4394682.jpg.2’ saved [211577/211577]



In [0]:
output_label = ['Dalai Lama','Arsene Wenger','Genelia Dsouza', 'Luiz Suarez', 'Sergio Aguero']

In [0]:
img_path = "/content/skysports-sergio-aguero-manchester_4394682.jpg"
img_array = cv2.imread(img_path)

new_path=[]
new_path = cv2.resize(img_array, (150,150))

#Convert to array and reshape
to_predict_data = np.array(new_path).reshape(1,150,150,3)
#Normalize
to_predict_data = to_predict_data/255

predicted_data = model.predict(to_predict_data)


In [38]:
print(predicted_data)
predicted_class = np.argmax(predicted_data)
print('Class index : ',predicted_class)
print('Prediction : Image is ',output_label[predicted_class])

[[2.6462294e-05 8.2824714e-05 4.2370147e-07 5.6118965e-02 9.4377136e-01]]
Class index :  4
Prediction : Image is  Sergio Aguero
